export const GET_FOOD_REQUEST="GET_FOOD_REQUEST";
export const GET_FOOD_FAIL="GET_FOOD_FAIL";
export const GET_FOOD_SUCCESS="GET_FOOD_SUCCESS";
export const GET_CART_FAIL="GET_CART_FAIL";
export const GET_CART_REQUEST="GET_CART_REQUEST";
export const GET_CART_SUCCESS="GET_CART_SUCCESS";